title: Prakritish Sen Eshore's Blog
author:
  name: Prakritish Sen Eshore
  email: blog@seneshore.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Welcome to our blog site, your go-to destination for a diverse range of insights 
  and discussions. Our blog is a dynamic platform where we explore and share knowledge 
  on a wide spectrum of topics, including DevOps, CI/CD, programming, essential tools, 
  and more. We are passionate about technology, software development, and best practices, 
  and our blog is designed to serve as a valuable resource for both beginners and experts 
  alike. Whether you're seeking tutorials, tips, or in-depth analyses, we've got you 
  covered. Join us on this exciting journey through the ever-evolving world of tech, 
  and let's explore, learn, and grow together.

url: "https://blog.seneshore.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: prakritish
github_username:  prakritish
linkedin_username: prakritish
author: Prakritish Sen Eshore
google_analytics: G-7KN27TP1J4

# Build settings

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  social_links:
  #   - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #   - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #   - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
    - { platform: github,         user_url: "https://github.com/prakritish/" }
  #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #   - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/prakritish" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #   - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #   - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
    - { platform: x,              user_url: "https://x.com/prakritish" }
  #   - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
# header_pages:
#   - about.md

# Set to `true` to show excerpts on the homepage.
#
show_excerpts: true
